name: Test Code

on:
    push:
#        branches: [main]
    pull_request:
        branches: [ main ]

jobs:
    build:
        name: Build and publish Python distribution
        runs-on: ubuntu-18.04

        steps:
            - uses: actions/checkout@master
            - name: Initialize Python 3.8
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8
                  pip install django
            - name: Lint with flake8
              run: |
                  # stop the build if there are Python syntax errors or undefined names
                  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                  # exit-zero treats all errors as warnings.
                  flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            - name: Run Tests
              run: |
                  python load_tests.py